global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ① Spring Boot Actuator 스크랩
  - job_name: 'springboot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['zaply:8080']  # 호스트에서 띄운 Spring Boot

  # ② Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
