version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3100:3100'             # 호스트 3100 → 컨테이너 3100
    volumes:
      - ./loki/config:/etc/loki # Loki 설정 파일을 컨테이너에 마운트
    networks:
      - loki-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/config:/etc/promtail
      - ./logs:/var/log/springboot   # Spring Boot 로그를 기록할 폴더 마운트
    networks:
      - loki-net
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"                       # Prometheus UI
    volumes:
      - ./prometheus/config:/etc/prometheus:ro
    networks:
      - loki-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - loki-net
    depends_on:
      - loki

networks:
  loki-net:
    driver: bridge
