server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push   # Compose 네트워크 내부에서 loki 컨테이너를 서비스명으로 호출

scrape_configs:
  - job_name: springboot-logs
    static_configs:
      - targets: ['host.docker.internal'] # 이거 안쓴다네요?
        labels:
          job: spring-boot
          __path__: /var/log/springboot/*.log   # 마운트된 로그 디렉토리
